# Dockerfile.inference

FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy app and model
COPY serve_model.py .
COPY models/ models/

# Install pipenv and dependencies
COPY Pipfile Pipfile.lock ./
RUN pip install pipenv && \
    pipenv install --system --deploy --ignore-pipfile

# Expose FastAPI port
EXPOSE 8000

# Start the app
CMD ["uvicorn", "serve_model:app", "--host", "0.0.0.0", "--port", "8000"]
